global:
  scrape_interval: 15s  # Интервал сбора метрик (настраивается)

scrape_configs:
  - job_name: 'music_catalog_api'
    static_configs:
      - targets: ['127.0.0.1:8000']  # Адрес приложения FastAPI

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:16686"]