components:
  schemas:
    Album:
      properties:
        artist_id:
          title: Artist Id
          type: integer
        id:
          title: Id
          type: integer
        releaseDate:
          format: date
          title: Releasedate
          type: string
        title:
          title: Title
          type: string
        tracks:
          anyOf:
          - items:
              $ref: '#/components/schemas/Track'
            type: array
          - type: 'null'
          default: []
          title: Tracks
      required:
      - id
      - title
      - releaseDate
      - artist_id
      title: Album
      type: object
    Artist-Input:
      properties:
        albums:
          anyOf:
          - items:
              $ref: '#/components/schemas/Album'
            type: array
          - type: 'null'
          default: []
          title: Albums
        genre:
          title: Genre
          type: string
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
      required:
      - id
      - name
      - genre
      title: Artist
      type: object
    Artist-Output:
      properties:
        albums:
          anyOf:
          - items:
              $ref: '#/components/schemas/Album'
            type: array
          - type: 'null'
          default: []
          title: Albums
        genre:
          title: Genre
          type: string
        id:
          title: Id
          type: integer
        name:
          title: Name
          type: string
      required:
      - id
      - name
      - genre
      title: Artist
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Track:
      properties:
        album_id:
          title: Album Id
          type: integer
        duration:
          title: Duration
          type: string
        id:
          title: Id
          type: integer
        title:
          title: Title
          type: string
      required:
      - id
      - title
      - duration
      - album_id
      title: Track
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: API музыкального каталога с метриками
  title: Музыкальный каталог API
  version: 3.0.1
openapi: 3.1.0
paths:
  /album:
    get:
      operationId: get_albums_album_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Album'
                title: Response Get Albums Album Get
                type: array
          description: Successful Response
      summary: Get Albums
      tags:
      - album
    post:
      operationId: add_album_album_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Album'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Album'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Album
      tags:
      - album
  /artist:
    get:
      operationId: get_artists_artist_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Artist-Output'
                title: Response Get Artists Artist Get
                type: array
          description: Successful Response
      summary: Get Artists
      tags:
      - artist
    post:
      operationId: add_artist_artist_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Artist-Input'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist-Output'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Artist
      tags:
      - artist
  /artist/{artistId}:
    get:
      operationId: get_artist_by_id_artist__artistId__get
      parameters:
      - in: path
        name: artistId
        required: true
        schema:
          title: Artistid
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Artist-Output'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Get Artist By Id
      tags:
      - artist
  /metrics:
    get:
      operationId: get_metrics_metrics_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Get Metrics
  /track:
    get:
      operationId: get_tracks_track_get
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Track'
                title: Response Get Tracks Track Get
                type: array
          description: Successful Response
      summary: Get Tracks
      tags:
      - track
    post:
      operationId: add_track_track_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Track'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Track'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Add Track
      tags:
      - track
